
if(CMAKE_Fortran_COMPILER_ID STREQUAL GNU)
  set(old -w)
  unset(new)
  if(CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL 8)
    list(APPEND old -std=legacy)
    set(new -std=f2018)
  endif()
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL Intel)
  if(WIN32)
    set(old /w)
    set(new /stand:f18 /warn:declarations /W1)
  else()
    set(old -w)
    set(new stand f18 -warn declarations -W1)
  endif()
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL PGI)
  set(old -w)
  set(new -Mdclchk)
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL Flang)
  set(old -w)
endif()
