name: ci_macos

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - "**/*.py"
      - "**/*.m"
      - "**/meson.build"
      - ".github/workflows/ci_macos.yml"
  pull_request:


jobs:

  python:
    runs-on: macos-latest
    env:
        FC: gfortran-11
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - run: pip install .[tests]

    - run: pytest
